apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
  namespace: dwp-stage
  labels:
    app: blog-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
    spec:
      containers:
        - name: blog-backend
          image: 850756192530.dkr.ecr.us-east-1.amazonaws.com/dwp/blog:v1.0.10
          ports:
           - containerPort: 9090
          env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://nonprod-blog-database-1.c2xkoy8ygth3.us-east-1.rds.amazonaws.com:5432/stageblogdb?serverTimezone=UTC
          - name: SPRING_DATASOURCE_USERNAME
            value: stageuser
          - name: SPRING_DATASOURCE_PASSWORD
            value: stageuser
          - name: SERVER_PORT
            value: "9090"



            